// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://vnaopmzcgedbivuiiuyh.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZuYW9wbXpjZ2VkYml2dWlpdXloIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzI4NzA2MDYsImV4cCI6MjA0ODQ0NjYwNn0.YIhiNAWFmxB0aLwzUbZpmEBFNstewh3M6V9naRo-fnI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);